// Sender ID / client code -> display name.
// Mirrors ../../ClientLookup.gs (the Gmail/Apps Script version's CLIENT_LOOKUP).
// Keep both copies in sync whenever a new Sender ID needs to be mapped.
'use strict';

const CLIENT_LOOKUP = [
  { senderId: 'Empty SenderID', senderName: 'Empty SenderID' },
  { senderId: 'aua', senderName: 'Kinara' },
  { senderId: 'DEV7', senderName: 'Dev' },
  { senderId: 'mahaveer', senderName: 'Mahaveer' },
  { senderId: 'DEV9', senderName: 'Dev' },
  { senderId: 'DEV12', senderName: 'Dev' },
  { senderId: 'tezzract', senderName: 'LightFinTech' },
  { senderId: 'rkpfla', senderName: 'RamKrishna Pure Finance' },
  { senderId: 'training', senderName: 'Training' },
  { senderId: 'SAMFIN', senderName: 'SamFin' },
  { senderId: 'ZFIRST', senderName: 'ZielFirst' },
  { senderId: 'KINCAP', senderName: 'Kinara' },
  { senderId: 'norarc', senderName: 'NorthernArc' },
  { senderId: 'sudlif', senderName: 'SudLife' },
  { senderId: 'kinara', senderName: 'Kinara' },
  { senderId: 'kinaracapital', senderName: 'Kinara' },
  { senderId: 'northernarc', senderName: 'NorthernArc' },
  { senderId: 'meraqui', senderName: 'Meraqui' },
  { senderId: 'dev', senderName: 'Dev' },
  { senderId: 'dev1', senderName: 'Dev' },
  { senderId: 'dev2', senderName: 'Dev' },
  { senderId: 'dev3', senderName: 'Dev' },
  { senderId: 'dev4', senderName: 'Dev' },
  { senderId: 'dev5', senderName: 'Dev' },
  { senderId: 'dev6', senderName: 'Dev' },
  { senderId: 'matrix', senderName: 'Matrix' },
  { senderId: 'zfirst', senderName: 'ZielFirst' },
  { senderId: 'demo', senderName: 'Demo' },
  { senderId: 'a8', senderName: 'A8' },
  { senderId: 'savect', senderName: 'savect' },
  { senderId: 'hdbfsl', senderName: 'HDBFSL' },
  { senderId: 'TRAINING', senderName: 'Training' },
  { senderId: 'lightfintech', senderName: 'LightFinTech' },
  { senderId: 'ESAF', senderName: 'ESAF' },
  { senderId: 'mfil', senderName: 'MFIL' },
  { senderId: 'Rs', senderName: 'Rs' },
  { senderId: 'NORARC', senderName: 'NorthernArc' },
  { senderId: 'dev7', senderName: 'Dev' },
  { senderId: 'berarf', senderName: 'Berar Finance' },
  { senderId: 'dev16', senderName: 'Dev' },
  { senderId: 'DEV17', senderName: 'Dev' },
  { senderId: 'DEV16', senderName: 'Dev' },
  { senderId: 'DEV11', senderName: 'Dev' },
  { senderId: 'dev11', senderName: 'Dev' },
  { senderId: 'Autonom8', senderName: 'Autonom8' },
  { senderId: 'AUTOMN', senderName: 'AUTOMN' },
  { senderId: 'automn', senderName: 'AUTOMN' },
  { senderId: 'KINARA', senderName: 'Kinara' },
  { senderId: 'SUDLIF', senderName: 'SudLife' },
  { senderId: 'DEV5', senderName: 'Dev' },
  { senderId: 'samfin', senderName: 'SamFin' },
  { senderId: 'dev18', senderName: 'Dev' },
  { senderId: 'DEV15', senderName: 'Dev' },
  { senderId: 'Test', senderName: 'Test' },
  { senderId: 'sudlife', senderName: 'SudLife' },
  { senderId: 'dev13', senderName: 'Dev' },
  { senderId: 'DEV1', senderName: 'Dev' },
  { senderId: '', senderName: 'Unknown' },
  { senderId: 'a8apps', senderName: 'A8 Apps' },
  { senderId: 'dev17', senderName: 'Dev' },
  { senderId: 'berar', senderName: 'Berar Finance' },
  { senderId: 'DEV18', senderName: 'Dev' },
  { senderId: 'DEMO', senderName: 'Demo' },
  { senderId: 'samunnati', senderName: 'SamFin' },
  { senderId: 'dev15', senderName: 'Dev' },
  { senderId: 'svkarm', senderName: 'Svakarma' },
  { senderId: 'autonm', senderName: 'AUTOMN' },
  { senderId: 'hdbfs', senderName: 'HDBFSL' },
  { senderId: 'dev9', senderName: 'Dev' },
  { senderId: 'DEV6', senderName: 'Dev' },
  { senderId: 'dev14', senderName: 'Dev' },
  { senderId: '##organisation##', senderName: '##Organisation##' },
  { senderId: 'rkpfcp', senderName: 'RamKrishna Pure Finance' },
  { senderId: 'rkpflr', senderName: 'RamKrishna Pure Finance' },
  { senderId: 'RKPFLA', senderName: 'RamKrishna Pure Finance' },
  { senderId: 'RKPFLR', senderName: 'RamKrishna Pure Finance' },
  { senderId: 'RKPFCO', senderName: 'RamKrishna Pure Finance' },
  { senderId: 'varashaktihousing', senderName: 'Vara Shakti Housing' },
  { senderId: 'zielfintech', senderName: 'ZielFirst' },
  { senderId: 'dev8', senderName: 'Dev' },
];

module.exports = { CLIENT_LOOKUP };
